name:                webserverh
version:             0.1.0.0
github:              "AbrahamAlcaina/webserverh"
license:             BSD3
author:              "Abraham Alcaina"
maintainer:          "abraham.alcaina@gmail.com"
copyright:           "2018 Abraham Alcaina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AbrahamAlcaina/webserverh#readme>

dependencies:
- base >= 4.7 && < 5
- eventful-core
- eventful-sqlite
- eventful-memory
- safe
- stm

- persistent
- persistent-sqlite

library:
  source-dirs: src
  dependencies:
  - eventful-core
  - eventful-memory

executables:
  webserverh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webserverh    
    - scotty

tests:
  webserverh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webserverh
    - eventful-core
    - QuickCheck
    - hspec-discover
    - hspec
